## Overview  
The below Support Vector Machine Model is an assignment from an Udemy Machine Learning class 

https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/?utm_source=adwords&utm_medium=udemyads&utm_campaign=Python_v.PROF_la.EN_cc.US_ti.7380&utm_content=deal4584&utm_term=_._ag_78513466559_._ad_436603254913_._kw__._de_c_._dm__._pl__._ti_dsa-774930046209_._li_9030072_._pd__._&matchtype=b&gclid=Cj0KCQiA9P__BRC0ARIsAEZ6iriN81oGE4RLs6f0zCpoBHxAbJNchYTEvzNHU9QE-cNlYdKRtxqLnAAaAkiaEALw_wcB

## Problem Statement

Using the Scikit-Learn built in breast cancer dataset (a copy of the UCI ML Breast Cancer Wisconsin (Diagnostic) datasets), determine wheather test cases are Malignant or Benign

## Table of Contents  

* [Import Libraries](#import_libraries)
* [Import Data](#import_data)
* [Create DataFrame and Descriptive Metrics](#create_dataframe)
* [Data Preprocessing; check for nulls](#data_preprocessing)
* [Exploratory Data Analysis](#explore_data)
* [Splitting the data into training and testing sets](#split_data)
* [Create and Train the Model](#train_model)
* [Predictions from our Model](#predict)
* [Evaluation Metrics](#eval_metrics)
* [Gridsearch](#grid_search)
* [Predictions from Gridsearch Model](#gs_predict)

<a class="anchor" id="import_libraries"></a>
## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

<a class="anchor" id="import_data"></a>
## Import Data

For this project we are using an Scikit-Learn built in dataset:

In [2]:
#import sklearn dataset
from sklearn.datasets import load_breast_cancer

In [3]:
#call load_breast_cancer and assign to variable
cancer = load_breast_cancer()

In [8]:
#view keys and explore/understand data
print(cancer.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [11]:
#view description of dataset
#print(cancer.DESCR)

Attribute definitions:
- **radius** (mean of distances from center to points on the perimeter)
- **texture** (standard deviation of gray-scale values)
- **perimeter**
- **area**
- **smoothness** (local variation in radius lengths)
- **compactness** (perimeter^2 / area - 1.0)
- **concavity** (severity of concave portions of the contour)
- **concave points** (number of concave portions of the contour)
- **symmetry**
- **fractal dimension** ("coastline approximation" - 1)

<a class="anchor" id="create_dataframe"></a>
## Create DataFrame and Descriptive Metrics

In [24]:
#create a feature dataframe
df_feat = pd.DataFrame(data=cancer.data,columns=cancer.feature_names)

In [26]:
df_feat.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [22]:
#create a target class dataframe
df_target= pd.DataFrame(data=cancer['target'],columns=['Cancer'])

In [23]:
df_target.head()

Cancer
0       0
1       0
2       0
3       0
4       0

<a class="anchor" id="data_preprocessing"></a>
## Data Preprocessing; check for nulls  

In [11]:
customers.isnull().sum()

Email                   0
Address                 0
Avatar                  0
Avg. Session Length     0
Time on App             0
Time on Website         0
Length of Membership    0
Yearly Amount Spent     0
dtype: int64

<a class="anchor" id="explore_data"></a>
## Exploratory Data Analysis

Understanding the relationship between the feature attributes and the target variable

In [51]:
#sns.pairplot(df)

In [27]:
#sns.displot(df['Yearly Amount Spent'])

In [28]:
#create a correlation matrix, round to 2 decimal places
#correlation_matrix = customers.corr().round(2)
#correlation_matrix

In [29]:
#plot the correlation matrix as a heat map
#sns.heatmap(data=correlation_matrix,annot=True)

#sns.heatmap(data=df.corr().round(2),annot=True)


In [30]:
#sns.jointplot(x='Time on Website',y='Yearly Amount Spent',data=customers,kind='scatter')

In [31]:
#sns.jointplot(x='Time on App',y='Yearly Amount Spent',data=customers,kind='scatter')

In [32]:
#sns.jointplot(x='Time on App',y='Length of Membership',data=customers,kind='hex')

In [33]:
#sns.pairplot(customers)

In [34]:
#sns.lmplot(x='Length of Membership', y='Yearly Amount Spent', data=customers)

<a class="anchor" id="split_data"></a>
## Splitting the data into training and testing sets

Create feature and label datasets;

For the feature dataset, create a new dataset with only the feature attributes you want; using pandas or numpy 'concatenate'

In [35]:
X = df_feat

In [30]:
#X.head()

In [43]:
#Label dataframe (Y)

y = cancer['target']

In [32]:
#Y.head()

Split data into train and test sets

In [37]:
from sklearn.model_selection import train_test_split

In [44]:
#random_state = 5, to tie out to 'towards data science' tutorial
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

<a class="anchor" id="train_model"></a>
## Create and Train the Model

In [39]:
#import support vector classifier
from sklearn.svm import SVC

In [41]:
svm = SVC()

In [45]:
#fit to training data

svm.fit(X_train,y_train)

SVC()

<a class="anchor" id="predict"></a>
## Predictions from our Model

Fit the model to our Test data, then compare the predictions to the actual values

In [46]:
#pass in data the model hasn't seen before (feature data set of our test data)
predictions = svm.predict(X_test)

<a class="anchor" id="eval_metrics"></a>
## Evaluation Metrics

In [48]:
from sklearn.metrics import classification_report,confusion_matrix

In [52]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[ 56  10]
 [  3 102]]


              precision    recall  f1-score   support

           0       0.95      0.85      0.90        66
           1       0.91      0.97      0.94       105

    accuracy                           0.92       171
   macro avg       0.93      0.91      0.92       171
weighted avg       0.93      0.92      0.92       171



<a class="anchor" id="grid_search"></a>
## Gridsearch

Search for the optimal parameters for the model by performing a gridsearch (try out all possible combinations of parameters); also consider normalizing data as well

**GridSearchCV (Cross Validation)**: takes a dictionary that describes the parameters (param_grid) that should be tried and a model to train. The grid of parameters is defined as a dictionary, where the keys are the parameters and the values are the settings to be tested. 

GridSearchCV is a meta-estimator. It takes an estimator like SVC, and creates a new estimator, that behaves exactly the same - in this case, like a classifier. Add refit=True (refit: Refit an estimator using the best found parameters on the whole dataset.)and choose verbose to whatever number you want, higher the number, the more verbose (verbose just means the text output describing the process).

C & Gamma SVM parameter affect on Radial Basis Function (RBF) kernel: 
* C = controls the cost of misclassification on training data  
   * Large C value = low bias (because you penalize the cost of misclassification), high variance  
   * Smaller C value= higer bias, lower variance  
* gamma = defines how far the influence of a single training example reaches, with low values meaning ‘far’ and high values meaning ‘close’. The gamma parameters can be seen as the *inverse of the radius of influence of samples* selected by the model as support vectors.  
    * Large gamma value = higer bias, lower variance  

In [53]:
from sklearn.model_selection import GridSearchCV

In [54]:
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']} 

In [55]:
#instantiate GridSearchCV with the model and parameters
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)

In [56]:
#fit the estimator to your data
grid.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END .....................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV 2/5] END .....................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV 3/5] END .....................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV 4/5] END .....................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV 5/5] END .....................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV 1/5] END ...................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 2/5] END ...................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 3/5] END ...................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 4/5] END ...................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 5/5] END ...................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 1/5] END ..................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV 2/5] END ..................C=0.1, gamma=0.0

[CV 4/5] END ....................C=1000, gamma=1, kernel=rbf; total time=   0.0s
[CV 5/5] END ....................C=1000, gamma=1, kernel=rbf; total time=   0.0s
[CV 1/5] END ..................C=1000, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 2/5] END ..................C=1000, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 3/5] END ..................C=1000, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 4/5] END ..................C=1000, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 5/5] END ..................C=1000, gamma=0.1, kernel=rbf; total time=   0.0s
[CV 1/5] END .................C=1000, gamma=0.01, kernel=rbf; total time=   0.0s
[CV 2/5] END .................C=1000, gamma=0.01, kernel=rbf; total time=   0.0s
[CV 3/5] END .................C=1000, gamma=0.01, kernel=rbf; total time=   0.0s
[CV 4/5] END .................C=1000, gamma=0.01, kernel=rbf; total time=   0.0s
[CV 5/5] END .................C=1000, gamma=0.01, kernel=rbf; total time=   0.0s
[CV 1/5] END ...............

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

Inspect the best parameters; best_params_  attribute:

In [57]:
grid.best_params_

{'C': 1, 'gamma': 0.0001, 'kernel': 'rbf'}

Inspect the best estimator in the best\_estimator_ attribute:

In [58]:
grid.best_estimator_

SVC(C=1, gamma=0.0001)

<a class="anchor" id="gs_predict"></a>
## Predictions from Gridsearch Model

In [59]:
grid_predictions = grid.predict(X_test)

In [62]:
print('Predictions from Model with Gridsearch parameters:')
print('\n')
print(confusion_matrix(y_test,grid_predictions))
print('\n')
print(classification_report(y_test,grid_predictions))

Predictions from Model with Gridsearch parameters:


[[ 59   7]
 [  4 101]]


              precision    recall  f1-score   support

           0       0.94      0.89      0.91        66
           1       0.94      0.96      0.95       105

    accuracy                           0.94       171
   macro avg       0.94      0.93      0.93       171
weighted avg       0.94      0.94      0.94       171



In [63]:
print('Predictions from Model with default parameters:')
print('\n')
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

Predictions from Model with default parameters:


[[ 56  10]
 [  3 102]]


              precision    recall  f1-score   support

           0       0.95      0.85      0.90        66
           1       0.91      0.97      0.94       105

    accuracy                           0.92       171
   macro avg       0.93      0.91      0.92       171
weighted avg       0.93      0.92      0.92       171

